### ISSUE TITLE
Expose JMX port into Cassandra interface

### ISSUE THREAD

**Issue by smiklosovic** [nosan/embedded-cassandra#78]
Hi,

why is this not exposed and only some ports are?

It would be nice to have this exposed in Cassandra interface because when I am integrating this with other tooling which is talking to multiple Cassandra instances, I want to be able to distinguish one port / instance from the other.

**Comment by nosan** [comment]
Hi @smiklosovic,

I can add this port only in case if it was explicitly used during Cassandra creation.

I cannot rely on the default `JMX_PORT=7199` which is specified in `cassandra-env.sh` as it could be easily changed.

I also cannot parse the Cassandra output to find JMX local port because the following output was only introduced in `3.X.X` version.

> Configured JMX server at: service:jmx:rmi://127.0.0.1/jndi/rmi://127.0.0.1:52865/jmxrmi

If you want I can add `System Properties` (Startup Parameters) to `Cassandra` interface and then you will be able to get JMX local port, but still, you have to explicitly set JMX port.


```java
Cassandra cassandra;
cassandra.getSystemProperties().get("cassandra.jmx.local.port")
```
